services:
  frontend:
    image: node:18
    container_name: frontend-app
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: bash -c "npm install && npm run dev -- --host" # the --host flag exposes the application to external networks
    environment:
      - NODE_ENV=development
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge