services:
  frontend:
    image: node:18
    container_name: frontend-app
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "${PORT}:${PORT}"
    command: sh -c "npm install && npm run dev"
     environment:
      - NODE_ENV=${NODE_ENV}
      - API_URL=${API_URL}
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge