name: CI for CO2 App Frontend
 
on: 
  repository_dispatch:
    types: [deploy-frontend]
  push: 
    branches: 
      - main
 
jobs: 
  build: 
    runs-on: ubuntu-22.04
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm ci

      - name: Wait for backend to be ready
        run: |
          echo "Waiting for backend..."
          timeout 60 bash -c 'until curl -sf http://localhost:${PORT}; do echo "Backend is not ready yet..."; sleep 5; done'

      - name: Run linting
        run: |
          npm install eslint
          npm run lint

      - name: Run tests
        run: |
          npm test